### ISSUE TITLE
Lyrics download

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/iposonic#5]
Implement lyrics download

**Comment by sqrlmstr5000** [comment]
I think this would be a cool feature to have :)

**Comment by ioggstream** [comment]
Agree. If you need it I'll do it asap.

**Comment by ioggstream** [comment]
Basic lyric support in the lyric branch. Works on Android client.

@tsquillario feedback welcome

TODO: 
- use more than one lyric server
- local caching of lyrics

**Comment by ioggstream** [comment]
done caching.

**Comment by sqrlmstr5000** [comment]
ill have to setup a Ubuntu VM and get this installed so I can test it out w/ MiniSub

**Comment by ioggstream** [comment]
@tsquillario which OS are you using?

Some time ago I ran iposonic on windows xp (no mysql embedded) and it worked fine. I'lI create a ticket for iposonic on windows or whatever your os is...

**Comment by sqrlmstr5000** [comment]
Win7 64bit
